- id: ReduceHeatingForEmptyHome0
  alias: 0.1.0 Reduit le chauffage quand la maison est vide
  trigger:
  - platform: template
    value_template: ' {{ (states.proximity.home_vincent.state | float) > 1250 and
      (states.proximity.home_virginia.state | float) > 1250 }}'
  - at: '23:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.chauffage
      temperature: 17
    service: climate.set_temperature
- id: AugmentHeatingOnOccupiedHome0
  alias: 0.2.0 Monte le chauffage quand la maison n'est pas vide
  trigger:
  - for:
      minutes: 3
    platform: template
    value_template: ' {{ (states.proximity.home_vincent.state | float) < 1250 or (states.proximity.home_virginia.state
      | float) < 1250 }}'
  - at: '17:30:00'
    platform: time
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.chauffage
    service: climate.turn_on
  - data:
      entity_id: group.chauffage
      temperature: 20
    service: climate.set_temperature
- id: FermeVeluxLenaic
  alias: 1.0 Ferme le velux de Lenaïc
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.tdeg_lenaic.state | float) < 19 and (states.sensor.netatmo_terrasse_temperature.state         |
      float) < 18 and is_state(''cover.velux_lenaic'',''open'') }}'
  - platform: template
    value_template: '{{ (states.sensor.tdeg_lenaic.state | float) > 21 and (states.sensor.netatmo_terrasse_temperature.state         |
      float) > 22 and is_state(''cover.velux_lenaic'',''open'') }}'
  - platform: template
    value_template: '{{ ((states.sensor.netatmo_pluie_jardin_rain.state | float) >
      0.1 or is_state(''weather.ti_ar_kaerell'',''rainy'')) and is_state(''cover.velux_lenaic'',''open'')
      }}'
  action:
  - service: script.turn_on
    data:
      entity_id: script.close_velux_lenaic
- id: OuvreVeluxLenaic
  alias: 1.1 Ouvre le vélux de Lenaïc s'il fait assez frais dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.netatmo_terrasse_temperature.state         |
      float) < 21  and (states.sensor.tdeg_lenaic.state | float) > 22  and (states.cover.velux_lenaic.attributes.current_position    |
      float) < 95  and (states.sensor.netatmo_pluie_jardin_rain.state            |
      float) < 0.1 and not is_state(''weather.ti_ar_kaerell'',''rainy'') }}'
  action:
  - service: script.turn_on
    data:
      entity_id: script.open_velux_lenaic
- id: FermeVoletLenaic
  alias: 1.2 Ferme le volet de Lenaïc
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.netatmo_terrasse_temperature.state         |
      float) > 26 and (states.sensor.tdeg_lenaic.state | float) > 25 and is_state(''weather.ti_ar_kaerell'',''sunny'')
      and is_state(''cover.volet_lenaic'',''open'') }}'
  - event: sunset
    offset: 00:30
    platform: sun
  - entity_id: sensor.home
    platform: state
    to: empty
  action:
  - data:
      entity_id: script.secure_close_volet_lenaic
    service: script.turn_on
- id: FermeVeluxPalier
  alias: 2.0 Ferme le velux du palier
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.netatmo_palier_temperature.state   | float)
      < 19 and (states.sensor.netatmo_terrasse_temperature.state | float) < 18 and
      is_state(''cover.velux_palier'',''open'') }}'
  - platform: template
    value_template: '{{ (states.sensor.netatmo_palier_temperature.state   | float)
      > 21 and (states.sensor.netatmo_terrasse_temperature.state | float) > 22 and
      is_state(''cover.velux_palier'',''open'') }}'
  - platform: template
    value_template: '{{ ((states.sensor.netatmo_pluie_jardin_rain.state | float) >
      0.1 or is_state(''weather.ti_ar_kaerell'',''rainy'')) and is_state(''cover.velux_palier'',''open'')
      }}'
  action:
  - service: script.turn_on
    data:
      entity_id: script.close_velux_lenaic
- id: OuvreVeluxPalier
  alias: 2.1 Ouvre le vélux du palier s'il fait assez frais dehors
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.netatmo_terrasse_temperature.state       |
      float) < 21  and (states.sensor.netatmo_palier_temperature.state         | float)
      > 22  and (states.cover.velux_palier.attributes.current_position  | float) <
      95  and (states.sensor.netatmo_pluie_jardin_rain.state          | float) < 0.1
      and not is_state(''weather.ti_ar_kaerell'',''rainy'') }}'
  action:
  - service: script.turn_on
    data:
      entity_id: script.open_velux_lenaic
- id: FermeVoletPalier
  alias: 2.2 Ferme le volet du palier
  trigger:
  - platform: template
    value_template: '{{ (states.sensor.netatmo_terrasse_temperature.state | float)
      > 26 and (states.sensor.netatmo_palier_temperature.state   | float) > 25 and
      is_state(''weather.ti_ar_kaerell'',''sunny'') and is_state(''cover.volet_palier'',''open'')
      }}'
  action:
  - service: script.turn_on
    data:
      entity_id: script.secure_close_volet_lenaic
- id: '1578933646759'
  alias: log webhook
  description: ''
  trigger:
  - platform: webhook
    webhook_id: 0139a42bd40897717441be1a14a6466879f4a1fc91ecaae9886605baa349ec46
  condition:
  - condition: state
    entity_id: sensor.home
    state: empty
  action:
  - data_template:
      data:
        android:
          notification:
            image: '{{ trigger.json.snapshot_url }}'
      message: '{{ trigger.json.message }}'
      title: 'Camera Alert:'
    service: notify.mobile_app_oneplus_a6013
  - data_template:
      data:
        android:
          notification:
            image: '{{ trigger.json.snapshot_url }}'
      message: '{{ trigger.json.message }}'
      title: 'Camera Alert:'
    service: notify.mobile_app_pixel_4
