homeassistant:
  customize: !include includes/customize.yaml
  whitelist_external_dirs:
    - /config
    - /config/www/

cloud:
default_config:
map:
python_script:
stream:
sun:
uilogs:

http:
  server_port: 8124
  base_url: https://tiarkaerell.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
    
automation:       !include automations.yaml
automation old:   !include_dir_list includes/automations
binary_sensor:    !include_dir_list includes/binary_sensors
climate:          !include_dir_list includes/climates
google:           !include includes/google.yaml
google_assistant: !include includes/google_assistant.yaml
group:            !include includes/groups.yaml
hacs:             !include includes/hacs.yaml
input_boolean:    !include_dir_named includes/input_booleans
input_datetime:   !include includes/input_datetime.yaml
life360:          !include includes/life360.yaml
logger:           !include includes/logger.yaml
lovelace:         !include includes/lovelace.yaml
media_player:     !include_dir_list includes/media_players
mqtt:             !include includes/mqtt.yaml
netatmo:          !include includes/netatmo.yaml
notify:           !include_dir_list includes/notifies
proximity:        !include includes/proximity.yaml
remote:           !include_dir_list includes/remotes
scene:            !include scenes.yaml
script:           !include includes/scripts.yaml
sensor:           !include_dir_list includes/sensors
spotify:          !include includes/spotify.yaml
switch:           !include includes/switches.yaml
tahoma:           !include includes/tahoma.yaml
tahoma_extended:  !include includes/tahoma.yaml
tts:              !include includes/tts.yaml
weather:          !include includes/weather.yaml
zone:             !include includes/zones.yaml
zwave:            !include includes/zwave.yaml

device_tracker:
- platform: nmap_tracker
  interval_seconds: 10
  consider_home: 60
  hosts:
    - 192.168.0.1-255
- platform: tile
  username: !secret email
  password: !secret tile
