resources:
- url: /local/community/simple-thermostat/simple-thermostat.js
  type: module
- url: /local/community/decluttering-card/decluttering-card.js
  type: module
- url: /local/community/lovelace-multiple-entity-row/multiple-entity-row.js
  type: module
- url: /local/community/button-entity-row/button-entity-row.js
  type: module
- url: /local/community/lovelace-fold-entity-row/fold-entity-row.js
  type: module
- url: /local/community/travel-time-card/travel-time-card.js
  type: js
- url: /local/community/mini-graph-card-bundle.js
  type: module
- url: /local/community/custom-weather-card-chart.js
  type: module
- url: /local/community/vertical-stack-in-card-0.2.1/vertical-stack-in-card.js
  type: js
- url: /local/community/lovelace-home-feed-card/home-feed-card.js
  type: js
- url: /local/community/atomic_calendar/atomic_calendar.js
  type: module
- url: /local/community/lovelace-card-tools/card-tools.js
  type: js
- url: /local/community/lovelace-layout-card/layout-card.js
  type: js
- url: /local/community/banner-card/banner-card.js
  type: module
- url: /local/community/lovelace-slider-entity-row/slider-entity-row.js
  type: module
  
title: Ti Ar Kaerell
views:
# Onglet principal
- path: home
  title: Accueil
  cards: !include_dir_list ui/accueil

# Onglet Salon
- title: Rez de Chaussée
  path: rez
  badges:
  - entity: sensor.netatmo_ti_ar_kaerell_terrasse_temperature
    name: "Terrasse"
  cards: !include ui/rez.yaml

# Onglet Etage        
- path: etage
  title: Etage
  badges:
  - entity: sensor.netatmo_ti_ar_kaerell_terrasse_temperature
    name: "Terrasse"
  cards: !include_dir_list ui/etage

# Onglet Map
- path: map
  title: Carte
  cards: !include_dir_list ui/map

# Onglet Cameras
- path: cameras
  title: Caméras
  cards: !include ui/cameras.yaml

# Onglet Cast
- path: cast
  title: Cast
  cards:
  - type: entities
    title: Cast
    show_header_toggle: false
    entities:
      - type: cast
        view: rez
