alias: Set Qubino to Eco
trigger:
  platform: state
  entity_id: input_select.qubino_lenaic
  to: 'Eco'
action:
  service: light.turn_on
  entity_id: light.qubino_goap_zmnhjd1_flush_dimmer_pilot_wire_level_2
  data:
    brightness: 60

