alias: Set Qubino to Stop
trigger:
  platform: state
  entity_id: input_select.qubino_lenaic
  to: 'Eteint'
action:
  service: light.turn_on
  entity_id: light.qubino_radiateur_lenaic_level
  data:
    brightness: 0
