alias: Set Qubino to Anti Freeze
trigger:
  platform: state
  entity_id: input_select.qubino
  to: 'Hors Gel'
action:
  service: light.turn_on
  entity_id: light.qubino_radiateur_bureau_level
  data:
    brightness: 30
