alias: Set Qubino to Eco
trigger:
  platform: state
  entity_id: input_select.qubino
  to: 'Eco'
action:
  service: light.turn_on
  entity_id: light.qubino_radiateur_bureau_level
  data:
    brightness: 60

