alias: 'Aeotec Button 1 Pressed'
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.aeotec_limited_zwa003_nanomote_quad
    scene_id: 1
action:
- data:
    entity_id: input_boolean.nanomote_quad_1
  service: input_boolean.turn_on
- delay: '00:00:02'
- data:
    entity_id: input_boolean.nanomote_quad_1
  service: input_boolean.turn_off