alias: 'Notify scene'
trigger:
  platform: event
  event_type: zwave.scene_activated
action:
- service: notify.custom_log_file
  data_template:
    message: >-
     '{{ trigger.json }}'
     '{{ trigger.event.data }}'