alias: 'Remote pressed open door'
trigger:
- platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.aeotec_limited_zwa003_nanomote_quad
    scene_id: 4
    scene_data: 7680
- platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.aeon_labs_zw088_key_fob_gen5_3
    scene_id: 1
- platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.aeon_labs_zw088_key_fob_gen5_3
    scene_id: 3
- platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.aeon_labs_zw088_key_fob_gen5_4
    scene_id: 1
- platform: event
  event_type: zwave.scene_activated
  event_data:
    entity_id: zwave.aeon_labs_zw088_key_fob_gen5_4
    scene_id: 3
action:
- data:
    entity_id: input_boolean.open_door
  service: input_boolean.turn_on
- delay: '00:00:02'
- data:
    entity_id: input_boolean.open_door
  service: input_boolean.turn_off