- platform: wake_on_lan
  mac: B8:85:84:9C:21:32
  name: PC TaK
  host: 192.168.0.13
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: pc_tak
- platform: template
  switches:
    volets:
      value_template: >-
        {% if is_state('group.volets_all', 'closed') %}
          Off
        {% else %}
          On
        {% endif %}
      turn_on:
      - service: cover.open_cover
        entity_id: group.volets_all
      turn_off:
      - service: cover.close_cover
        entity_id: group.volets_all
      icon_template: >-
        {% if is_state('group.volets_all', 'closed') %}
          mdi:window-closed
        {% else %}
          mdi:window-open
        {% endif %}
    guest:
      value_template: >-
        {% if is_state('input_boolean.guest_at_home', 'on') %}
          On
        {% else %}
          Off
        {% endif %}
      turn_on:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_at_home
      - service: automation.turn_off
        entity_id: automation.0_1_0_reduit_le_chauffage_quand_la_maison_est_vide
      turn_off:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_at_home
      - service: automation.turn_on
        entity_id: automation.0_1_0_reduit_le_chauffage_quand_la_maison_est_vide
      icon_template: >-
        {% if is_state('input_boolean.guest_at_home', 'on') %}
          mdi:account-plus
        {% else %}
          mdi:account-off-outline
        {% endif %}
    ampli:
      value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') != 'PowerOff' }}"
      turn_on:
        service: script.spotify_salon
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "Ecouter de la musique"
      icon_template: >-
        {% if state_attr('remote.harmony_hub', 'current_activity') != 'PowerOff' %}
          mdi:play-circle
        {% else %}
          mdi:spotify
        {% endif %}
    television:
      value_template: "{{ state_attr('remote.harmony_hub', 'current_activity') != 'PowerOff' }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: "Regarder la TV"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
        data:
          activity: "Regarder la TV"
      icon_template: >-
        {% if state_attr('remote.harmony_hub', 'current_activity') != 'PowerOff' %}
          mdi:youtube-tv
        {% else %}
          mdi:television
        {% endif %}
    toggle_velux_palier:
      value_template: "{{ is_state('cover.velux_palier','open') }}"
      turn_on:
        service: script.open_velux_palier
      turn_off:
        service: script.close_velux_palier
      icon_template: >-
        {% if is_state('cover.velux_palier','open') %}
          mdi:lock-open
        {% else %}
          mdi:lock
        {% endif %}
    toggle_volet_palier:
      value_template: "{{ is_state('cover.volet_palier','open') }}"
      turn_on:
        service: script.secure_open_volet_palier
      turn_off:
        service: script.secure_close_volet_palier
      icon_template: >-
        {% if is_state('cover.volet_palier','open') %}
          mdi:lock-open
        {% else %}
          mdi:lock
        {% endif %}
    toggle_both_palier:
      value_template: "{{ is_state('cover.velux_palier','open') or is_state('cover.volet_palier','open') }}"
      turn_on:
        service: script.open_both_palier
      turn_off:
        service: script.close_both_palier
      icon_template: >-
        {% if is_state('cover.velux_palier','open') or is_state('cover.volet_palier','open') %}
          mdi:lock-open
        {% else %}
          mdi:lock
        {% endif %}
    toggle_velux_lenaic:
      value_template: "{{ is_state('cover.velux_lenaic','open') }}"
      turn_on:
        service: script.open_velux_lenaic
      turn_off:
        service: script.close_velux_lenaic
      icon_template: >-
        {% if is_state('cover.velux_lenaic','open') %}
          mdi:lock-open
        {% else %}
          mdi:lock
        {% endif %}
    toggle_volet_lenaic:
      value_template: "{{ is_state('cover.volet_lenaic','open') }}"
      turn_on:
        service: script.secure_open_volet_lenaic
      turn_off:
        service: script.secure_close_volet_lenaic
      icon_template: >-
        {% if is_state('cover.volet_lenaic','open') %}
          mdi:lock-open
        {% else %}
          mdi:lock
        {% endif %}
    toggle_both_lenaic:
      value_template: "{{ is_state('cover.velux_lenaic','open') or is_state('cover.volet_lenaic','open') }}"
      turn_on:
        service: script.open_both_lenaic
      turn_off:
        service: script.close_both_lenaic
      icon_template: >-
        {% if is_state('cover.velux_lenaic','open') or is_state('cover.volet_lenaic','open') %}
          mdi:lock-open
        {% else %}
          mdi:lock
        {% endif %}