- platform: wake_on_lan
  mac: B8:85:84:9C:21:32
  name: PC TaK
  host: 192.168.0.13
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: pc_tak
- platform: template
  switches:
    aeration_etage:
      value_template: >-
        {% if is_state('group.velux_etage', 'open') %}
          On
        {% else %}
          Off
        {% endif %}
      turn_on:
      - service: script.aerer_etage
      turn_off:
      - service: script.close_both_lenaic
      - service: script.close_both_palier
      icon_template: >-
        {% if is_state('group.velux_palier','open') %}
          mdi:lock-open
        {% else %}
          mdi:lock
        {% endif %}
    volets:
      value_template: >-
        {% if is_state('group.volets_all', 'closed') %}
          Off
        {% else %}
          On
        {% endif %}
      turn_on:
      - service: cover.open_cover
        entity_id: group.volets_all
      turn_off:
      - service: cover.close_cover
        entity_id: group.volets_all
      icon_template: >-
        {% if is_state('group.volets_all', 'closed') %}
          mdi:window-shutter
        {% else %}
          mdi:window-shutter-open
        {% endif %}
    guest:
      value_template: >-
        {% if is_state('input_boolean.guest_at_home', 'on') %}
          On
        {% else %}
          Off
        {% endif %}
      turn_on:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_at_home
      - service: automation.turn_off
        entity_id: automation.0_1_0_reduit_le_chauffage_quand_la_maison_est_vide
      turn_off:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_at_home
      - service: automation.turn_on
        entity_id: automation.0_1_0_reduit_le_chauffage_quand_la_maison_est_vide
      icon_template: >-
        {% if is_state('input_boolean.guest_at_home', 'on') %}
          mdi:account-plus
        {% else %}
          mdi:account-off-outline
        {% endif %}
    ampli:
      value_template: "{{ is_state_attr('remote.harmony', 'current_activity', 'Ecouter de la musique') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony
        data:
          activity: "Ecouter de la musique"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony
        data:
          activity: "Ecouter de la musique"
      icon_template: >-
        {% if state_attr('remote.harmony', 'current_activity') == 'Ecouter de la musique' %}
          mdi:play-circle
        {% else %}
          mdi:spotify
        {% endif %}
    television:
      value_template: "{{ is_state_attr('remote.harmony', 'current_activity', 'Regarder la TV') }}"
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony
        data:
          activity: "Regarder la TV"
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony
        data:
          activity: "Regarder la TV"
      icon_template: >-
        {% if state_attr('remote.harmony', 'current_activity') == 'Regarder la TV' %}
          mdi:youtube-tv
        {% else %}
          mdi:television
        {% endif %}
    tele_plex:
      value_template: "{{ states('media_player.sony_bravia_tv') }}"
      turn_on:
        service: script.allumer_plex
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony
        data:
          activity: "Regarder la TV"
      icon_template: >-
        {% if is_state('media_player.sony_bravia_tv',' on') %}
          mdi:youtube-tv
        {% else %}
          mdi:television
        {% endif %}
    tele_molotov:
      value_template: "{{ states('media_player.sony_bravia_tv') }}"
      turn_on:
        service: script.allumer_molotov
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony
        data:
          activity: "Regarder la TV"
      icon_template: >-
        {% if is_state('media_player.sony_bravia_tv',' on') %}
          mdi:youtube-tv
        {% else %}
          mdi:television
        {% endif %}
    velux_palier:
      value_template: "{{ state_attr('cover.velux_palier','current_position')|int > 13}}"
      turn_on:
        service: cover.set_cover_position
        data:
          entity_id: cover.velux_palier
          position: 100
      turn_off:
        service: cover.set_cover_position
        data:
          entity_id: cover.velux_palier
          position: 12
      icon_template: >-
        {% if state_attr('cover.velux_palier','current_position')|int > 13 %}
          hass:window-open
        {% else %}
          hass:window-closed
        {% endif %}
    velux_lenaic:
      value_template: "{{ state_attr('cover.velux_lenaic','current_position')|int > 13}}"
      turn_on:
        service: cover.set_cover_position
        data:
          entity_id: cover.velux_lenaic
          position: 100
      turn_off:
        service: cover.set_cover_position
        data:
          entity_id: cover.velux_lenaic
          position: 12
      icon_template: >-
        {% if state_attr('cover.velux_lenaic','current_position')|int > 13 %}
          hass:window-open
        {% else %}
          hass:window-closed
        {% endif %}
    volet_cuisine:
      value_template: "{{ is_state('cover.volet_cuisine','open') }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.volet_cuisine
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.volet_cuisine
      icon_template: >-
        {% if is_state('cover.volet_cuisine','open') %}
          hass:window-shutter-open
        {% else %}
          hass:window-shutter
        {% endif %}
    volet_entree:
      value_template: "{{ is_state('cover.volet_entree','open') }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.volet_entree
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.volet_entree
      icon_template: >-
        {% if is_state('cover.volet_entree','open') %}
          hass:window-shutter-open
        {% else %}
          hass:window-shutter
        {% endif %}
    volet_salon:
      value_template: "{{ is_state('cover.volet_salon','open') }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.volet_salon
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.volet_salon
      icon_template: >-
        {% if is_state('cover.volet_salon','open') %}
          hass:window-shutter-open
        {% else %}
          hass:window-shutter
        {% endif %}
    volet_bureau:
      value_template: "{{ is_state('cover.volet_bureau','open') }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.volet_bureau
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.volet_bureau
      icon_template: >-
        {% if is_state('cover.volet_bureau','open') %}
          hass:window-shutter-open
        {% else %}
          hass:window-shutter
        {% endif %}
    volets_parents:
      value_template: "{{ is_state('cover.volet_parents','open') }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.volet_parents
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.volet_parents
      icon_template: >-
        {% if is_state('cover.volet_parents','open') %}
          hass:window-shutter-open
        {% else %}
          hass:window-shutter
        {% endif %}